export const LAB_USER_CREATE_URL = "accounts/lab-user/"
export const PATIENT_USER_CREATE_URL = "accounts/patient-user/"
export const GET_TOKEN_URL = "accounts/get-token/"
export const GET_ALL_BILLS = "bill/bill-view/"
export const GET_ALL_TESTS = "bill/test/"
export const GET_ALL_PATIENT = "accounts/patient-user/"
export const CREATE_BILL = "bill/bill-view/"